Разметка главной страницы
htmlacademy-htmlcss/1508967-sedona-29 pull request #2
Opened 2020-09-13 12:29 UTC by Codarocker

2020-09-14 06:36 UTC, urazaev requested changes
Хорошая первичная разметка, много сделано правильно. Кое что нужно поменять, не много.

2020-09-14 06:36 UTC, urazaev commented on index.html
>  <!DOCTYPE html>
Прогони обязательно файл в валидаторе https://validator.w3.org/nu/
`error` быть не должно, `warning` допустимы
В основном ругается на отсутствие alt у изображений.

2020-09-14 06:36 UTC, urazaev commented on index.html
> +  </a>
Структурно делать ссылкой эту часть смысла нету, она не есть ссылка, тут скорее фоновое изображение гор и в разметке его быть не должно, а вот текст с приветствием это да вполне себе контентное изображение в разметке нормально будет, кроме этого имей ввиду что именовать файлы нужно в одном регистре, то есть за место `Welcome.svg` должно быть `welcome.svg`

2020-09-14 06:36 UTC, urazaev commented on index.html
> +    <img src="domik.svg">
Иконки это не контентные изображения, декоративные, в разметку не ставим их все.

2020-09-14 06:36 UTC, urazaev commented on index.html
> +
Не забудь добавить коричневую кнопку https://yadi.sk/d/ILrLJsQoBNXang

2020-09-14 06:36 UTC, urazaev commented on index.html
> +  <img src="youtube.svg">
Тут тоже иконки сугубо декоративные в разметку нет необходимости их ставить через тег `img` но вот ссылки это будут три разные по этому их тут нужно прописать.

2020-09-14 06:54 UTC, Codarocker commented on index.html
> +  <img src="youtube.svg">
Все замечания понятны кроме иконок, не совсем понял тегом img для их вставки не пользоваться? А как тогда обернуть в тег <a>  а как подставить ссылку на само изображение иконки?

2020-09-14 06:58 UTC, urazaev commented on index.html
> +  <img src="youtube.svg">
пока просто заведи три ссылки `a href` а потом на лекции про декоративные элементы нас научат как подставлять декоративные изображения

2020-09-14 07:01 UTC, Codarocker commented on index.html
> +  <img src="youtube.svg">
Ок

2020-09-15 08:33 UTC, urazaev requested changes
Почти готово)

2020-09-15 08:33 UTC, urazaev commented on index.html
> +  <a href="youtube.svg"></a>
ссылки на страницы соцсетей должны быть, по скольку мы не знаем пока точных адресов `href` можно оставить или пустым или просто на заглушку сделать `href="#"`

2020-09-15 09:33 UTC, Codarocker commented on index.html
> +  <a href="youtube.svg"></a>
Просто три ссылки без обозначения что это твиттер и так далее оставить?

2020-09-15 10:58 UTC, Codarocker commented on index.html
> +  <a href="youtube.svg"></a>
Отправил, надеюсь все правильно понял

2020-09-16 07:23 UTC, urazaev commented on index.html
> +  <a href="youtube.svg"></a>
Да структурно так более правильно, ты все понял корректно, задание принимаю)

2020-09-16 07:23 UTC, merged