Базовая стилизация Index.html
htmlacademy-htmlcss/1508967-sedona-29 pull request #4
Opened 2020-09-24 06:22 UTC by Codarocker

2020-09-24 11:55 UTC, urazaev requested changes
Почти готовая работа, давай немного дошлифуем)

2020-09-24 11:55 UTC, urazaev commented on css/style.css
> +  position: absolute;
position пока вообще не будем давай использовать, по скольку мы пока не умеем корректно с ним работать.

2020-09-24 11:55 UTC, urazaev commented on css/style.css
> +}
у ссылок в навигации при наведении должен меняться цвет согласно стайлгайду

2020-09-24 11:55 UTC, urazaev commented on css/style.css
> +  position: absolute;
Тут и везде далее

2020-09-24 11:55 UTC, urazaev commented on index.html
> +    <p class="footer_credits">website by</p>
ссылку эту тоже стилизуй как в макете

2020-09-25 06:30 UTC, Codarocker commented on css/style.css
> +}
Точно, я что пропустил)

2020-09-25 06:42 UTC, Codarocker commented on index.html
> +    <p class="footer_credits">website by</p>
Лого html академии не очень понял как посмотреть цвет, я так понимаю это svg будет? Поставил пока толь надпись: website by на ссылку, надеюсь правильно)

2020-09-26 04:25 UTC, merged